config:
  package:
    name: name
    version: 0.0.1
    author: author name
    email: author@example.com
  schema:
    schema_path: ./prisma/models.prisma
    clients:
    - id: python
      lang: python
      path: ./prisma/python.prisma
